stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/iris.csv
    - src/prepare.py
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    - src/train.py
    outs:
    - model.pkl
